### model
model_name_or_path: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/merged_dpo_260520_ps2400clean_ckpt138_for_closing_dpo
adapter_name_or_path: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/dpo_260520_closing_budget_clean_from_ckpt138_r32_2epoch_ctx24576_z3nooffload_label_logits_4gpu0123/checkpoint-66
trust_remote_code: true
flash_attn: auto

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid
deepspeed: /work/liweihan/wyf/helloagents-trip-planner/training/configs/deepspeed/ds_z3_no_offload_config.json

### dataset
dataset_dir: /work/liweihan/wyf/helloagents-trip-planner/training/data/llamafactory
dataset: trip_planner_dpo_260520_closing_budget_clean_train
eval_dataset: trip_planner_dpo_260520_closing_budget_clean_val
template: qwen
cutoff_len: 24576
preprocessing_num_workers: 4
dataloader_num_workers: 1

### output
output_dir: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/dpo_260521_closing_budget_clean_continue_from_ckpt66_r32_2epoch_lr1p5e6_ctx24576_z3nooffload_label_logits_4gpu0123
logging_steps: 1
save_strategy: steps
save_steps: 16
save_total_limit: 6
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.5e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
do_eval: false
per_device_eval_batch_size: 1
eval_strategy: "no"
