### model
model_name_or_path: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/merged_sft_260516_final1200_for_dpo
trust_remote_code: true
flash_attn: fa2

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid
deepspeed: /work/liweihan/wyf/helloagents-trip-planner/training/configs/deepspeed/ds_z3_offload_torchadam_config.json

### dataset
dataset_dir: /work/liweihan/wyf/helloagents-trip-planner/training/data/llamafactory
dataset: trip_planner_dpo_260517_fd600_planner_soft_direct402_train
eval_dataset: trip_planner_dpo_260517_fd600_planner_soft_direct402_val
template: qwen
cutoff_len: 26000
preprocessing_num_workers: 4
dataloader_num_workers: 1

### output
output_dir: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/dpo_260518_fd600_planner_soft_direct402_r16_4epoch_z3offload_torchadam_fa2_5gpu01234
logging_steps: 1
save_strategy: steps
save_steps: 5
save_total_limit: 8
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-6
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
do_eval: false
per_device_eval_batch_size: 1
eval_strategy: "no"
