### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
adapter_name_or_path: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/sft_v3_260513_replay_usage700_plus_bestofn1200_from_final_r32_b32_lr1e5_ctx24576_ep2_retry_20260513_1026
trust_remote_code: true
flash_attn: auto

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset_dir: /work/liweihan/wyf/helloagents-trip-planner/training/data/llamafactory
dataset: trip_planner_dpo_260516_bestofn1200_filtered_long20_train
eval_dataset: trip_planner_dpo_260516_bestofn1200_filtered_long20_val
template: qwen
cutoff_len: 24576
preprocessing_num_workers: 4
dataloader_num_workers: 1

### output
output_dir: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/dpo_260516_final1200_filtered_long20_memtest_full_logits_5gpu
logging_steps: 1
save_strategy: "no"
plot_loss: false
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
max_steps: 1
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
do_eval: false
per_device_eval_batch_size: 1
eval_strategy: "no"
