### model
model_name_or_path: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/merged_dpo_260519_core1418_plus_direct402_ckpt126_for_next_dpo
adapter_name_or_path: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/dpo_260519_ps2400clean_plus_direct402_from_ckpt126_r32_3epoch_ctx24576_z3nooffload_label_logits_6gpu012345/checkpoint-138
template: qwen
trust_remote_code: true
flash_attn: auto
infer_dtype: bfloat16
export_device: cpu
export_dir: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/merged_dpo_260520_ps2400clean_ckpt138_for_closing_dpo
export_size: 5
export_legacy_format: false
