### model
model_name_or_path: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/merged_dpo_260520_ps2400clean_ckpt138_for_closing_dpo
adapter_name_or_path: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/dpo_260520_closing_budget_clean_from_ckpt138_r32_2epoch_ctx24576_z3nooffload_label_logits_4gpu0123/checkpoint-66
template: qwen
trust_remote_code: true
flash_attn: auto
infer_dtype: bfloat16
export_device: cpu
export_dir: /work/liweihan/wyf/helloagents-trip-planner/training/outputs/qwen25_7b/merged_dpo_260521_closing_ckpt66_for_continue_dpo
export_size: 5
export_legacy_format: false
