### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
trust_remote_code: true
flash_attn: fa2
use_unsloth_gc: true

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target: all
deepspeed: training/configs/shared/ds_z3_param_offload_config.json

### dataset
dataset_dir: training/data/llamafactory
dataset: trip_planner_260509_main_clean_train
eval_dataset: trip_planner_260509_main_clean_test
template: qwen
cutoff_len: 24576
overwrite_cache: false
preprocessing_num_workers: 2
dataloader_num_workers: 0

### output
output_dir: training/outputs/qwen25_7b/sft_260509_main_clean_official_r32_b32_lr6e5_ctx24576_warm10_20260510
logging_steps: 1
save_strategy: "no"
plot_loss: false
overwrite_output_dir: true
save_only_model: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
num_train_epochs: 4.0
learning_rate: 6.0e-5
lr_scheduler_type: cosine
warmup_steps: 10
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000

### eval
per_device_eval_batch_size: 1
eval_strategy: epoch
